In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
df = pd.read_csv("career_path_matrix.csv")

In [3]:
df

,career_path,prerequisites
0,Python Backend Developer,"python,flask,django,fastapi,sql,mysql,postgres..."
1,Java Backend Developer,"java,spring,spring_boot,hibernate,maven,sql,my..."
2,Node.js Backend Developer,"javascript,nodejs,express,mongodb,sql,rest_api..."
3,React Frontend Developer,"html,css,javascript,typescript,react,redux,nex..."
4,Angular Frontend Developer,"html,css,javascript,typescript,angular,rxjs,bo..."
5,MERN Stack Developer,"mongodb,express,react,nodejs,javascript,html,c..."
6,MEAN Stack Developer,"mongodb,express,angular,nodejs,typescript,html..."
7,Data Analyst,"sql,excel,power_bi,tableau,python,pandas,data_..."
8,Data Scientist,"python,pandas,numpy,statistics,matplotlib,seab..."
9,Machine Learning Engineer,"python,numpy,pandas,scikit_learn,tensorflow,py..."


In [4]:
career_list = df['prerequisites'].tolist()
career_list

['python,flask,django,fastapi,sql,mysql,postgresql,rest_api,git,docker,jwt,aws',
 'java,spring,spring_boot,hibernate,maven,sql,mysql,rest_api,git,docker,microservices',
 'javascript,nodejs,express,mongodb,sql,rest_api,git,docker,jwt,redis',
 'html,css,javascript,typescript,react,redux,nextjs,tailwind,bootstrap,git,responsive_design',
 'html,css,javascript,typescript,angular,rxjs,bootstrap,git,responsive_design',
 'mongodb,express,react,nodejs,javascript,html,css,git,rest_api,jwt,docker',
 'mongodb,express,angular,nodejs,typescript,html,css,git,rest_api,docker',
 'sql,excel,power_bi,tableau,python,pandas,data_visualization,statistics',
 'python,pandas,numpy,statistics,matplotlib,seaborn,scikit_learn,machine_learning,sql,jupyter',
 'python,numpy,pandas,scikit_learn,tensorflow,pytorch,deep_learning,mlops,docker,git',
 'python,tensorflow,pytorch,cnn,rnn,lstm,transformers,computer_vision,nlp,gpu',
 'python,machine_learning,deep_learning,tensorflow,pytorch,llms,langchain,rag,vector_database,

In [5]:
user_skills = "python,flask,sql"
# user_skills = (",").join("selected_skill")

In [6]:
document= career_list + [user_skills]
document

['python,flask,django,fastapi,sql,mysql,postgresql,rest_api,git,docker,jwt,aws',
 'java,spring,spring_boot,hibernate,maven,sql,mysql,rest_api,git,docker,microservices',
 'javascript,nodejs,express,mongodb,sql,rest_api,git,docker,jwt,redis',
 'html,css,javascript,typescript,react,redux,nextjs,tailwind,bootstrap,git,responsive_design',
 'html,css,javascript,typescript,angular,rxjs,bootstrap,git,responsive_design',
 'mongodb,express,react,nodejs,javascript,html,css,git,rest_api,jwt,docker',
 'mongodb,express,angular,nodejs,typescript,html,css,git,rest_api,docker',
 'sql,excel,power_bi,tableau,python,pandas,data_visualization,statistics',
 'python,pandas,numpy,statistics,matplotlib,seaborn,scikit_learn,machine_learning,sql,jupyter',
 'python,numpy,pandas,scikit_learn,tensorflow,pytorch,deep_learning,mlops,docker,git',
 'python,tensorflow,pytorch,cnn,rnn,lstm,transformers,computer_vision,nlp,gpu',
 'python,machine_learning,deep_learning,tensorflow,pytorch,llms,langchain,rag,vector_database,

In [7]:
vectorizer = TfidfVectorizer()

In [8]:
tfidf_matrix = vectorizer.fit_transform(document)
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 193 stored elements and shape (21, 107)>

In [9]:
from sklearn.metrics.pairwise import cosine_similarity

In [10]:
similarity_scores = cosine_similarity(
    tfidf_matrix[-1],
    tfidf_matrix[:-1]
)

In [11]:
similarity_scores

array([[0.44924653, 0.11727272, 0.1431576 , 0.        , 0.        ,
        0.        , 0.        , 0.23529654, 0.21330343, 0.1039286 ,
        0.08704334, 0.08941404, 0.        , 0.        , 0.        ,
        0.08524197, 0.        , 0.        , 0.        , 0.        ]])

In [12]:
best_match = similarity_scores.argmax()
best_match

np.int64(0)

In [13]:
career_list[best_match]

'python,flask,django,fastapi,sql,mysql,postgresql,rest_api,git,docker,jwt,aws'

In [14]:
match =similarity_scores.argsort()

In [15]:
match

array([[ 3,  6,  5,  4, 14, 12, 13, 16, 19, 18, 17, 15, 10, 11,  9,  1,
         2,  8,  7,  0]])

In [27]:
ranked_indices = similarity_scores.argsort()[::-1].flatten()

In [28]:
top_indices = ranked_indices[:5]
top_indices

array([0, 7, 8, 2, 1])

In [29]:
for i in range(5):
    print(career_list[top_indices[i]])

python,flask,django,fastapi,sql,mysql,postgresql,rest_api,git,docker,jwt,aws
sql,excel,power_bi,tableau,python,pandas,data_visualization,statistics
python,pandas,numpy,statistics,matplotlib,seaborn,scikit_learn,machine_learning,sql,jupyter
javascript,nodejs,express,mongodb,sql,rest_api,git,docker,jwt,redis
java,spring,spring_boot,hibernate,maven,sql,mysql,rest_api,git,docker,microservices


In [30]:
df.iloc[top_indices]

,career_path,prerequisites
0,Python Backend Developer,"python,flask,django,fastapi,sql,mysql,postgres..."
7,Data Analyst,"sql,excel,power_bi,tableau,python,pandas,data_..."
8,Data Scientist,"python,pandas,numpy,statistics,matplotlib,seab..."
2,Node.js Backend Developer,"javascript,nodejs,express,mongodb,sql,rest_api..."
1,Java Backend Developer,"java,spring,spring_boot,hibernate,maven,sql,my..."


In [31]:
for index in top_indices:
    career = df.iloc[index]

    # print("Career:", career["career"])
    print("Skills:", career["career_path"])
    print("Prerequisites:", career["prerequisites"])
    print("-----------------------")

Skills: Python Backend Developer
Prerequisites: python,flask,django,fastapi,sql,mysql,postgresql,rest_api,git,docker,jwt,aws
-----------------------
Skills: Data Analyst
Prerequisites: sql,excel,power_bi,tableau,python,pandas,data_visualization,statistics
-----------------------
Skills: Data Scientist
Prerequisites: python,pandas,numpy,statistics,matplotlib,seaborn,scikit_learn,machine_learning,sql,jupyter
-----------------------
Skills: Node.js Backend Developer
Prerequisites: javascript,nodejs,express,mongodb,sql,rest_api,git,docker,jwt,redis
-----------------------
Skills: Java Backend Developer
Prerequisites: java,spring,spring_boot,hibernate,maven,sql,mysql,rest_api,git,docker,microservices
-----------------------


In [32]:
similarity_scores = similarity_scores.flatten()

In [33]:
top_indices

array([0, 7, 8, 2, 1])

In [34]:
print(similarity_scores)

[0.44924653 0.11727272 0.1431576  0.         0.         0.
 0.         0.23529654 0.21330343 0.1039286  0.08704334 0.08941404
 0.         0.         0.         0.08524197 0.         0.
 0.         0.        ]


In [55]:
# Create user skill set once
user_skill_set = {skill.strip().lower() for skill in user_skills.split(",")}

for index in top_indices:

    career = df.iloc[index]

    score = similarity_scores[index] * 100

    # Required skills for this career
    required_skill_set = set(career["prerequisites"].split(","))

    # Skill Gap Analysis
    matched_skills = user_skill_set & required_skill_set
    missing_skills = required_skill_set - user_skill_set

    matched_count = len(matched_skills)
    required_count = len(required_skill_set)

    # Display Recommendation
    print("=" * 60)
    print("Career:", career["career_path"])
    print("Match Score:", round(score, 2), "%")

    print(f"\nWhy this match?")
    print(f" Matched {matched_count} out of {required_count} required skills.")

    print("\nSkills You Already Have:")
    if matched_skills:
        print(", ".join(sorted(matched_skills)))
    else:
        print("None")

    print("\n Skills You Need to Learn:")
    if missing_skills:
        print(", ".join(sorted(missing_skills)))
    else:
        print("None! You already have all the required skills.")

    print("=" * 60)
    if score >= 80:
        print("\n⭐ Excellent Match!")
        print("Your profile strongly aligns with this career.")
        print("You already possess most of the required skills.")
        print("Continue learning the remaining skills to become job-ready.")

    elif score >= 60:
        print("\n👍 Good Match!")
        print("You have a solid foundation for this career.")
        print("Learning the missing skills will significantly improve your profile.")

    else:
        print("\n📚 Learning Path Recommended!")
        print("This career is achievable, but you'll need to build several core skills.")
        print("Focus on the missing skills listed below.")

Career: Python Backend Developer
Match Score: 44.92 %

Why this match?
 Matched 3 out of 12 required skills.

Skills You Already Have:
flask, python, sql

 Skills You Need to Learn:
aws, django, docker, fastapi, git, jwt, mysql, postgresql, rest_api

📚 Learning Path Recommended!
This career is achievable, but you'll need to build several core skills.
Focus on the missing skills listed below.
Career: Data Analyst
Match Score: 23.53 %

Why this match?
 Matched 2 out of 8 required skills.

Skills You Already Have:
python, sql

 Skills You Need to Learn:
data_visualization, excel, pandas, power_bi, statistics, tableau

📚 Learning Path Recommended!
This career is achievable, but you'll need to build several core skills.
Focus on the missing skills listed below.
Career: Data Scientist
Match Score: 21.33 %

Why this match?
 Matched 2 out of 10 required skills.

Skills You Already Have:
python, sql

 Skills You Need to Learn:
jupyter, machine_learning, matplotlib, numpy, pandas, scikit_learn, 

In [44]:
user_skill_set = set(user_skills.split(","))

In [45]:
user_skill_set

{'flask', 'python', 'sql'}

In [46]:
required_skill_set

{'docker',
 'git',
 'hibernate',
 'java',
 'maven',
 'microservices',
 'mysql',
 'rest_api',
 'spring',
 'spring_boot',
 'sql'}

Why this match? You have 1 out of 11 required skills.


In [58]:
# Create user skill set once
user_skill_set = {skill.strip().lower() for skill in user_skills.split(",")}

# Store all recommendations
recommendations = []

for index in top_indices:

    career = df.iloc[index]
    score = similarity_scores[index] * 100

    # Required skills
    required_skill_set = set(career["prerequisites"].split(","))

    # Skill Gap Analysis
    matched_skills = user_skill_set & required_skill_set
    missing_skills = required_skill_set - user_skill_set

    matched_count = len(matched_skills)
    required_count = len(required_skill_set)

    # AI Recommendation Message
    if score >= 80:

        if missing_skills:
            message = (
                f"⭐ Excellent Match!\n"
                f"Your profile strongly aligns with this career.\n"
                f"You already have {matched_count} out of {required_count} required skills.\n"
                f"Focus on learning: {', '.join(sorted(missing_skills))}"
            )
        else:
            message = (
                f"⭐ Excellent Match!\n"
                f"Amazing! You already possess all the required skills for this career."
            )

    elif score >= 60:

        message = (
            f"👍 Good Match!\n"
            f"You already have {matched_count} out of {required_count} required skills.\n"
            f"Learning these skills will strengthen your profile:\n"
            f"{', '.join(sorted(missing_skills))}"
        )

    else:

        message = (
            f"📚 Learning Path Recommended!\n"
            f"This career is achievable, but you'll need to build several core skills.\n"
            f"You currently have {matched_count} out of {required_count} required skills.\n"
            f"Start learning:\n"
            f"{', '.join(sorted(missing_skills))}"
        )

    # Store recommendation
    recommendation = {
        "career": career["career_path"],
        "score": round(score, 2),
        "message": message,
        "matched_count": matched_count,
        "required_count": required_count,
        "matched_skills": sorted(matched_skills),
        "missing_skills": sorted(missing_skills),
    }

    recommendations.append(recommendation)